player.onChat("1", function () {
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.move(FORWARD, 2)
    agent.move(RIGHT, 2)
    agent.place(DOWN)
    agent.move(LEFT, 1)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.place(DOWN)
    agent.move(RIGHT, 1)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.place(DOWN)
    agent.move(LEFT, 1)
    agent.place(DOWN)
    agent.setItem(OAK_DOOR, 64, 1)
    agent.move(LEFT, 1)
    agent.move(DOWN, 2)
    agent.place(DOWN)
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.move(UP, 2)
    agent.place(DOWN)
    agent.move(LEFT, 1)
    for (let index = 0; index < 3; index++) {
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.turn(RIGHT_TURN)
    agent.move(LEFT, 1)
    for (let index = 0; index < 2; index++) {
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.move(DOWN, 2)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.setItem(GLASS, 64, 1)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.place(DOWN)
    for (let index = 0; index < 2; index++) {
        agent.move(LEFT, 1)
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.turn(RIGHT_TURN)
    agent.move(LEFT, 1)
    for (let index = 0; index < 5; index++) {
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.turn(RIGHT_TURN)
    agent.move(LEFT, 1)
    for (let index = 0; index < 1; index++) {
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.move(DOWN, 2)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.setItem(GLASS, 64, 1)
    agent.place(DOWN)
    agent.move(UP, 1)
    agent.setItem(PLANKS_OAK, 64, 1)
    agent.place(DOWN)
    agent.move(LEFT, 1)
    for (let index = 0; index < 2; index++) {
        agent.move(DOWN, 2)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(UP, 1)
        agent.place(DOWN)
        agent.move(LEFT, 1)
    }
    agent.setItem(LOG_OAK, 64, 1)
    agent.move(UP, 1)
    agent.move(FORWARD, 1)
    agent.move(RIGHT, 1)
    for (let index = 0; index < 4; index++) {
        for (let index = 0; index < 4; index++) {
            agent.place(DOWN)
            agent.move(FORWARD, 1)
        }
        agent.move(BACK, 4)
        agent.move(RIGHT, 1)
    }
})
